### PR TITLE
Filling new branches and tweaking Jets filling

### PR DESCRIPTION
**Pull request by yiiyama**
- Double-b tagger is moved to an EDProducer in Auxiliary so that the tag info can be included in the pat FatJet in makeFatJets_cff
- QGLikelihood included in makeJets_cff and is available as userFloat in the pat Jet
- prod.py updated
- Made another MET filler to fill various flavors of METs
- Filling the new branches

### CODE REVIEW

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/
- Run steps: https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/1/flowGraphTable

**Comment by mitsidekick** [comment]
Problem compiling. See https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/1/console

**Comment by dabercro** [comment]
Jenkins is looking at `master` in PandaPhysics' PandaTree, hence the compilation error. Feel free to change these lines to a branch that you expect to work while developing: https://github.com/PandaPhysics/PandaProd/blob/branch-010-devel/Jenkinsfile#L6-L7.

**Comment by dabercro** [comment]
Ah. We might want to put `SCRAM_ARCH` up there too: https://github.com/PandaPhysics/PandaProd/blob/branch-010-devel/Jenkinsfile#L11

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/
- Run steps: https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/2/flowGraphTable

**Comment by mitsidekick** [comment]
Problem compiling. See https://t3serv003.mit.edu/job/PandaPhysics/job/PandaProd/job/PR-59/2/console

**Pull request merged**
