### PR TITLE
changes for 010 version campaign (prod)

### PR DESCRIPTION
**Pull request by DylanHsu**

### CODE REVIEW

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/
- Run steps: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/1/flowGraphTable

**Comment by mitsidekick** [comment]
Problem compiling. See https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/1/console

**Comment by DylanHsu** [comment]
compilation problem reason: library `PhysicsTools/TensorFlow/interface/TensorFlow.h` is not available in CMSSW_9_4_4, we need version 9_4_6

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/
- Run steps: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/2/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/data/Run2017D/MET/MINIAOD/17Nov2017-v1/00000/E0A114B0-56F1-E711-8C5F-44A842B46A7E.root
- /store/mc/RunIIFall17MiniAOD/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/94X_mc2017_realistic_v10-v1/00000/023E56A6-4FF3-E711-867C-68B59972C49E.root

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIFall17MiniAOD/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/94X_mc2017_realistic_v10-v1/00000/023E56A6-4FF3-E711-867C-68B59972C49E.root. See https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2017D/MET/MINIAOD/17Nov2017-v1/00000/E0A114B0-56F1-E711-8C5F-44A842B46A7E.root. See https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-63/2/console

**Pull request merged**
