### PR TITLE
Fill puppi

### PR DESCRIPTION
**Pull request by dabercro**
The alternate to https://github.com/PandaPhysics/PandaTree/pull/131 is to just fill the PUPPI weights this way in the new CMSSW. This would give analysis code less to do since PandaTree would not have to do anything differently, but some of the precision is lost when changing the packed format.

@yiiyama @sidnarayanan do you have a preference for PR? I would go with the change to PandaTree myself, but matching the packing format can always wait until a full update for legacy analyses.

### CODE REVIEW

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-74/
- Run steps: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-74/1/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/data/Run2018A/MET/MINIAOD/PromptReco-v2/000/316/505/00000/7C75991C-535C-E811-B931-FA163E3A8726.root
- /store/data/Run2018A/SingleMuon/MINIAOD/PromptReco-v2/000/316/615/00000/7E2944AD-145E-E811-90D7-FA163E11797A.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018C/SingleMuon/MINIAOD/PromptReco-v3/000/319/991/00000/2EDB9039-5E8E-E811-85C3-FA163E7DE62A.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root

**Comment by mitsidekick** [comment]
Tests passed! See plots at:

- http://t3serv001.mit.edu/~jenkins/relval/?d=PandaPhysics/PandaProd/PR-74/1

**Comment by yiiyama** [comment]
I prefer this solution to PandaPhysics/PandaTree#131. Keeping the packed values in general was done to minimize the precision loss as you note, but it shouldn't be done at the price of making the analysis code complicated / tricky to use.
It would be great if there is a way to switch between using the exposer and just using the float values depending on the input file type, but you shouldn't waste your time finding that switch either.

**Comment by dabercro** [comment]
I'm not sure how it does it, but the new version of CMSSW also exposes the new packed format for the old input files. So even Run2018A is still correct with this PR: http://t3serv001.mit.edu/~jenkins/relval/PandaPhysics/PandaProd/PR-74/1/SingleMuon_2018A_0/pfCandidates/puppiW_log.pdf

Unfortunately, PandaProd as is here keeps hanging on MC. It happens either in PFCandFiller or HLTFiller, and it seems to change when I add print statements to try to debug :( Hopefully that's not something we need to figure out to start running on the new data though.

**Pull request merged**
