### PR TITLE
Branch 003 prod

### PR DESCRIPTION
**Pull request by yiiyama**
prod.py was reshuffled, so it's hard to see what's going on from the diff.

In essence we now do:
- If 03Feb2017, do egFix but not muFix
- If MC or 23Sep2016, do muFix but not egFix

If egFix is True, both slimmedMETs and slimmedMETsPuppi are corrected with GS fix. slimmedMETsPuppi is overwritten, but slimmedMETs is duplicated into slimmedMETsMuEGClean (which is the original GS-fixed MET name in MINIAOD).

If muFix is True, all references to packedPFCandidates is replaced with cleanMuonsPFCandidates (i.e. everything that runs on top of packedPFCandidates will be running on cleanMuonsPFCandidates), and MET is recomputed.

### CODE REVIEW

**Comment by sidnarayanan** [comment]
This looks good to me, but before merging to master, we should figure out how we want to do the development cycle:

- Tag 002 so that it can be checked out retroactively 
- Should development be done on master or should there be a separate 00N branch where all PRs are directed, and then a single PR at the end into master? Since we've already made PRs to master for 003 we can start this for N>3.

**Comment by yiiyama** [comment]
I've tagged 002 already at the commit that includes bugfixes but no feature updates.
I am fine with either way. I guess you prefer to have a 00N branch, so yes for N>3 we should follow that model. And maybe say the bugfixes still go to master?

**Comment by yiiyama** [comment]
This is the tag:
https://github.com/PandaPhysics/PandaProd/tree/prod-002

**Comment by yiiyama** [comment]
We need to fix photon ID, but first merging to the devel branch to make debugging easier.

**Pull request merged**
