### PR TITLE
Cleanup for 10_2_X

### PR DESCRIPTION
**Pull request by yiiyama**
Dropped a bunch of old POG recipes from setuprel and also streamlined prod.py a bit.
Added more options.configs so we now have the full suite of configs for legacy Run 2.

With more than 6 config options, I decided that we need to make a conceptual change to the way prod.py is organized. Until now, options.config was an *optional* parameter that serves as a global switch to change individual parameters (like whether to reapply JEC), but now I made it mandatory and am using the values of options.config in various parts of prod.py to modify the sequences.

### CODE REVIEW

**Comment by yiiyama** [comment]
ah I forgot to fix the puppi weights filling. Relval will fail at least on those..

**Comment by yiiyama** [comment]
And another thing: can we upgrade the release used by Jenkins? This PR is written in 10_2_15 to take advantage of some POG update that isn't available in earlier 10_2s. It should be equivalent to applying a POG recipe through setuprel.sh on an earlier 10_2, so the output should be compatible with existing 014 files.

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_50_120/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/592C4C53-9E40-3A4C-8E5C-854C8D7021C3.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/console

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIAutumn18MiniAOD/ZToMuMu_NNPDF31_13TeV-powheg_M_50_120/MINIAODSIM/102X_upgrade2018_realistic_v15-v2/120000/592C4C53-9E40-3A4C-8E5C-854C8D7021C3.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/console

**Comment by dabercro** [comment]
@yiiyama Yeah, that's easy to do in the `Jenkinsfile` in the repo root. Just change the `cmssw_version` value.

**Comment by dabercro** [comment]
Also, for 014, I found that it was nice that `options.config` was optional, so I can just give something like [this](https://github.com/dabercro/PandaProd/blob/2016-rereco-102X/Producer/cfg/data.py) to Christoph without having to change `prod.py` or anything. Is there still a way to change the other parameters easily?

**Comment by yiiyama** [comment]
globaltag can be overwritten, but not isData. So if you want to do something similar, you take an existing data config (say 2018Prompt) as base but then override the globaltag.

**Comment by yiiyama** [comment]
Because we have many configs now, it was becoming impossible to deduce the config name from the LFN alone in the JenkinsFile. I changed the ~jenkins/miniaod/*.txt file format to have the config name explicitly set in the second row of each file. I hope this doesn't break everything.

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root
- /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root
- /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root
- /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/2/console

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root
- /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root
- /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root
- /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root. See https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/3/console

**Comment by yiiyama** [comment]
Hmm the errors are all over the place.. Fixing them one by one.

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/4/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root
- /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root
- /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root
- /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root

**Comment by mitsidekick** [comment]
Tests passed! See plots at:

- http://t3serv001.mit.edu/~jenkins/relval/?d=PandaPhysics/PandaProd/PR-80/4

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/5/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root
- /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root
- /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root
- /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root

**Comment by mitsidekick** [comment]
Tests passed! See plots at:

- http://t3serv001.mit.edu/~jenkins/relval/?d=PandaPhysics/PandaProd/PR-80/5

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/
- Run steps: https://t3serv002.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-80/1/flowGraphTable

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/mc/RunIIAutumn18MiniAOD/WZ_TuneCP5_13TeV-pythia8/MINIAODSIM/102X_upgrade2018_realistic_v15-v1/120000/3E56C96C-1935-FB42-BCE8-E09BA813F441.root
- /store/mc/RunIIFall17MiniAODv2/DYBJetsToLL_M-50_Zpt-200toInf_TuneCP5_13TeV-madgraphMLM-pythia8/MINIAODSIM/PU2017_12Apr2018_94X_mc2017_realistic_v14-v1/50000/460A12B6-3F72-E811-A61A-FA163E19E2C3.root
- /store/mc/RunIISummer16MiniAODv3/TT_TuneCUETP8M2T4_13TeV-powheg-pythia8/MINIAODSIM/PUMoriond17_94X_mcRun2_asymptotic_v3-v1/110000/B22320DB-EBBC-E811-A987-14187763B811.root
- /store/data/Run2018C/SingleMuon/MINIAOD/17Sep2018-v1/120000/86D3C5F3-C2F0-4B4B-ADB7-413EF9C94C38.root
- /store/data/Run2018D/SingleMuon/MINIAOD/PromptReco-v2/000/324/315/00000/EDA1C953-5E41-FF4B-BF50-E7FE0F46962F.root
- /store/data/Run2017E/SingleMuon/MINIAOD/31Mar2018-v1/90000/AA13B7F5-A938-E811-82CE-0CC47A7C356A.root
- /store/data/Run2016C/SingleMuon/MINIAOD/17Jul2018-v1/20000/A04390E4-219B-E811-B4A7-002590FD5E82.root

**Comment by mitsidekick** [comment]
Tests passed! See plots at:

- http://t3serv001.mit.edu/~jenkins/relval/?d=PandaPhysics/PandaProd/PR-80/1

**Pull request closed without merging**
