### PR TITLE
ECF refactor

### PR DESCRIPTION
**Pull request by sidnarayanan**
Rewriting the ECF calculator, mainly to make it more maintainable. The refactor also gives performance improvements for N < 4, but since we usually run up to N = 4, we won't notice this. I spent a while trying to improve the performance of answering the question "what are the 2 (or 3) smallest elements of a 6-element set?", but at the end of the day, the old algorithm was the best empirically.

### CODE REVIEW

**Comment by mitsidekick** [comment]
Starting tests! You can follow along (if on T3).

- Job: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-61/
- Run steps: https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-61/1/flowGraphTable

**Comment by dabercro** [comment]
This test will still fail on `branch-010-devel`... Usually the fastest way to do a partial sort is to make a heap: http://en.cppreference.com/w/cpp/algorithm/make_heap. I don't know if it would help much for 6 elements though.

**Comment by mitsidekick** [comment]
Finished compiling! Will try to run over:

- /store/data/Run2017D/MET/MINIAOD/17Nov2017-v1/00000/E0A114B0-56F1-E711-8C5F-44A842B46A7E.root
- /store/mc/RunIIFall17MiniAOD/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/94X_mc2017_realistic_v10-v1/00000/023E56A6-4FF3-E711-867C-68B59972C49E.root

**Comment by mitsidekick** [comment]
Problem producing with /store/mc/RunIIFall17MiniAOD/TTJets_TuneCP5_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/94X_mc2017_realistic_v10-v1/00000/023E56A6-4FF3-E711-867C-68B59972C49E.root. See https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-61/1/console

**Comment by mitsidekick** [comment]
Problem producing with /store/data/Run2017D/MET/MINIAOD/17Nov2017-v1/00000/E0A114B0-56F1-E711-8C5F-44A842B46A7E.root. See https://t3serv003.mit.edu:8040/job/PandaPhysics/job/PandaProd/job/PR-61/1/console

**Comment by sidnarayanan** [comment]
@dabercro, that's what `std::partial_sort` does, but the time it takes to build a heap and the associated memory allocation actually makes it one of the worst options I tested. Just to clarify what I tried:
- Build a heap and sort (~1s/event)
- Partial look-backwards insertion sort (involves a few copies) (~800ms/event)
- Partial look-forwards sort (uses swap instead, but this involves copying pointers) (~500ms/event)
- Explicit loop-and-copy (involves exactly 2 copies, 6 integer comparisons, and 11 float comparisons) (~350 ms/event)

> This test will still fail on branch-010-devel..

Is this a problem with the test or my PR?

**Comment by dabercro** [comment]
Okay, I'm not surprised. I didn't check what you did.

The test failed because the config files are still not right for 9_4_4.

**Comment by dabercro** [comment]
`setupDoubleBTag() takes at least 6 arguments (5 given)` which is different than the old error. I don't know that anyone fixed those either though.

**Comment by sidnarayanan** [comment]
Anyone object to me merging this despite the failing build? Looks like it's unrelated. I did test this locally and it looked fine.

**Comment by dabercro** [comment]
Yeah, it's unrelated. I should have said that explicitly.

**Comment by dabercro** [comment]
Do you have it working in 9_4_X or something else?

**Comment by sidnarayanan** [comment]
9_4_0

**Comment by sidnarayanan** [comment]
Er sorry no, 8_0_29. I am getting an unrelated crash on 9_4_0. Something to do with electron smearing. But this really should have nothing to do with the CMSSW version.

**Comment by yiiyama** [comment]
so config=Fall17 didn't fix it?

**Comment by dabercro** [comment]
Ah, I also realized. I overheard you guys talking about `prod.py`. Are you also modifying `data.py` and `mc.py`? That's what Jenkins is testing.

**Comment by sidnarayanan** [comment]
Ah no, I am only dealing with `prod.py`. Can Jenkins just test `prod.py` with different configs? I think we usually propagate changes to `data.py` and `.mc.py` before a new release. 

And @yiiyama yeah sorry, I was confusing myself. Specifying the right config did make it work, but I did not get a chance to run the ECF tests in 94x. I'll put that on my to-do list.

**Comment by dabercro** [comment]
I personally don't like that as much because the point of Jenkins is to prove that Kraken will work out of the box.

**Pull request merged**
